# Generated by Django 4.2.7 on 2023-12-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='detail_status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'Entregado')], default='P', max_length=1, verbose_name='Estado de la orden'),
        ),
    ]
