# Generated by Django 4.2.7 on 2023-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderdetails_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='detail_status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('L', 'Listo'), ('E', 'Entregado')], default='P', max_length=1, verbose_name='Estado de la orden'),
        ),
    ]
