# Generated by Django 4.2.7 on 2023-12-03 19:33

import apps.user.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=10, unique=True, validators=[apps.user.models.ecuadorian_dni_validator], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('waiter', 'Mesero'), ('cashier', 'Cajero'), ('chef', 'Cocinero')], max_length=7, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(code='invalid_phone', message='El número de teléfono debe contener solo números.', regex='^[0-9]+$')], verbose_name='Teléfono'),
        ),
    ]
