# Generated by Django 4.2.7 on 2023-12-03 19:32

import apps.main.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), apps.main.models.ecuadorian_dni_validator], verbose_name='Cédula')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Solo se permiten letras')], verbose_name='Nombre')),
                ('surname', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Solo se permiten letras')], verbose_name='Apellido')),
                ('address', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\s]+$', 'No se permiten caracteres especiales')], verbose_name='Dirección')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(code='invalid_phone', message='El número de teléfono debe contener solo números.', regex='^[0-9]+$')], verbose_name='Teléfono')),
            ],
        ),
    ]
