# Generated by Django 4.2.7 on 2023-12-03 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio unitario')),
                ('iva', models.CharField(choices=[('12.00', '12.00'), ('0.00', '0.00')], default='0.00', max_length=5, verbose_name='IVA')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
                ('description', models.CharField(max_length=35, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairs_number', models.IntegerField(default=1, verbose_name='Número de sillas')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=10, verbose_name='Género'),
        ),
    ]
