# Generated by Django 4.2.7 on 2023-12-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_table_client_email_client_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
    ]
