# Generated by Django 4.2.7 on 2024-01-11 19:44

import apps.main.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=35, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\s]+$', 'No se permiten caracteres especiales')], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), apps.main.models.ecuadorian_dni_validator], verbose_name='Cédula'),
        ),
    ]
