# Generated by Django 4.2.7 on 2024-01-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('commercial_name', models.CharField(max_length=50, verbose_name='Nombre Comercial')),
                ('stablishement_address', models.CharField(max_length=50, verbose_name='Dirección Establecimiento')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['id'],
            },
        ),
    ]
