# Generated by Django 4.2.7 on 2024-01-13 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(code='invalid_phone', message='El número de teléfono debe contener solo números.', regex='^[0-9]+$')], verbose_name='Teléfono'),
        ),
    ]
